### ISSUE TITLE
prepare for playload animation

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#63]
When there is a match and its large enough to warrant queuing up garbage, particles should fly towards the first panel in the match. This is to imply a playload is about to be sent to the other player.

#### Tasks
- [ ] particles are specific to characters, so particles must be easily swappable
- [ ] particles must be deterministic for multiplayer

#### Research

This requires game-mechanics research, [ask the experts](https://github.com/omenking/swap-n-pop/wiki/Research-Assistance-for-Game-Mechanics).

- [ ] the animation initial delay might vary based on size of garbage?
