### ISSUE TITLE
clearing chain garbage should clear chain garbage that is touching nearby

### ISSUE THREAD

**Issue by omenking** [omenking/swap-n-pop#69]
When you complete a match that is touching chain garbage. And there is chain garbage touching that garbage and so forth. All chain garbage touching should be marked for clearing. However only 1 row of garbage will actually clear. So the player has to match multiple times to clear chain garbage.

### Tasks
- [ ] ensure this has [integration tests](https://github.com/omenking/swap-n-pop/wiki/Writing-Test-Code) eg. `garbage_spec.js`

#### Research

This requires game-mechanics research, [ask the experts](https://github.com/omenking/swap-n-pop/wiki/Research-Assistance-for-Game-Mechanics).

- [ ] can chain combo clear combo garbarge?
- [ ] what is the exact logic of how chain garbage shrinks in size? 1 row at a time?

### Related TIckets
